### ISSUE TITLE
AES算法ECB模式安全问题

### ISSUE THREAD

**Issue by kazaf0z** [esastack/esa-commons#18]
AES加密算法的ECB模式是不安全的，现阶段有很多公司的安全加密规范是禁止使用AES/ECB模式的。

问题所在处：esa/commons/SecurityUtils.java
![image](https://user-images.githubusercontent.com/9592084/103510337-ff9a4900-4e9f-11eb-9f3a-39921bf2eb3f.png)

不建议使用AES/ECB加密模式。

**Comment by alalag1** [comment]
是的，
可以将AES#ECB部分标记为@Deprecated，并在将来的一个非向下兼容的版本中移除
https://github.com/esastack/esa-commons/blob/611cebb7c562c10cd29e374c66527a5269a57390/commons/src/main/java/esa/commons/SecurityUtils.java#L403-L437
@kazaf0z 请确认SecurityUtils#ThreeDes中的ECB是否也需要标记为@Deprecated
https://github.com/esastack/esa-commons/blob/611cebb7c562c10cd29e374c66527a5269a57390/commons/src/main/java/esa/commons/SecurityUtils.java#L309-L334
