### ISSUE TITLE
StringUtils#concat() would append the string "null" to the result

### ISSUE THREAD

**Issue by wfxssky** [esastack/esa-commons#26]
### Problem Lies
esa/commons/StringUtils.java

### Problem behavior
Users always notice if the params is null, it will not append the string "null" to the result
![rBAoL2CKexiAJCfrAABqV0GHTVQ689](https://user-images.githubusercontent.com/26199064/116531889-39d99b80-a912-11eb-9c14-8a035ff673ae.png)

However, if the number of params is less than 5, it will append the string "null" to the result which is not in line with users' expectations.
![rBAoL2CKexiABiPdAAA1UrnJmqQ705](https://user-images.githubusercontent.com/26199064/116532110-79a08300-a912-11eb-8d8e-e30241545ecd.png)

I think it is also necessary to judge whether the param is null when the number of params is less than 5.

**Comment by alalag1** [comment]
PRs are welcome!
